# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Eucharistie-info Vlaanderen
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Eucharistie live volgen op internet. Uurrooster, teksten en links.
baseurl: "/streaming-links" # the subpath of your site, e.g. /blog
url: "https://eucharistie.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
#remote_theme: pages-themes/primer
plugins:
  - jekyll-feed
  - jekyll-octicons
  # - jekyll-seo-tag

collections:
  kanalen:
    output: true

sass:
  sass_dir: assets/css/
  load_paths:
    - node_modules/

gems:
  - jekyll-octicons

# Caution: arrays will be entirely overwritten by entries in other config files
# if used (like_config-dev.yml). So you might want to copy all the defaults to
# that file before adding more.
defaults:
  - scope:
      path: ""
      type: kanalen
    values:
      layout: stream
      route: channel
  - scope:
      path: ""
    values:
      image: /assets/img/logo-social.png
      lang: nl_BE

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
